from sail import Tensor 
from typing import List, Set, Dict, Tuple, Optional, Type


def xavier_uniform(x1: Tensor, gain: float = 1.0) -> Tensor: ...
def kaiming_uniform(x1: Tensor, mode: str = "fan_in", nonlin: str = "leaky_relu") -> Tensor: ...
def xavier_normal(x1: Tensor, gain: float = 1.0) -> Tensor: ...
def kaiming_normal(x1: Tensor, mode: str = "fan_in", nonlin: str = "leaky_relu") -> Tensor: ...
