/*
################################################################################
#                  THIS CODE IS AUTOGENERATED FROM A TEMPLATE                  #
#                 TO MAKE CHANGES, EDIT THE ORIGINAL .src FILE                 #
################################################################################
*/

#pragma once 

#include <Python.h>
#include "numpy/arrayobject.h"
#include <structmember.h>
#include "../../src/Tensor.h"
#include "../../src/ops/elementwise.h"
#include "../py_tensor/py_tensor.h"
#include <chrono>
#include <iostream>

#include "../macros.h"

/** begin block
 * name = [add, sub, mul, div]
 * op = [+, -, *, /]
 */


RETURN_OBJECT ops_add(PyObject* self, PyObject *args) {

    PyTensor* t1;
    PyTensor* t2;

    if (!PyArg_ParseTuple(args, "OO", &t1, &t2)) {
        PyErr_SetString(PyExc_TypeError, "Inputs should be Sail Tensors");
        return NULL;
    }

    BINARY_TENSOR_TYPE_CHECK(t1, t2);

    PyTensor* ret_class;
    ret_class = (PyTensor *) PyTensorType.tp_alloc(&PyTensorType, 0);

    ret_class->tensor = ((PyTensor*)t1)->tensor + ((PyTensor*)t2)->tensor;

    ret_class->ndim = ((PyTensor*)t1)->ndim;
    ret_class->dtype = ((PyTensor*)t1)->dtype;

    return (PyObject *) ret_class;
}



RETURN_OBJECT ops_sub(PyObject* self, PyObject *args) {

    PyTensor* t1;
    PyTensor* t2;

    if (!PyArg_ParseTuple(args, "OO", &t1, &t2)) {
        PyErr_SetString(PyExc_TypeError, "Inputs should be Sail Tensors");
        return NULL;
    }

    BINARY_TENSOR_TYPE_CHECK(t1, t2);

    PyTensor* ret_class;
    ret_class = (PyTensor *) PyTensorType.tp_alloc(&PyTensorType, 0);

    ret_class->tensor = ((PyTensor*)t1)->tensor - ((PyTensor*)t2)->tensor;

    ret_class->ndim = ((PyTensor*)t1)->ndim;
    ret_class->dtype = ((PyTensor*)t1)->dtype;

    return (PyObject *) ret_class;
}



RETURN_OBJECT ops_mul(PyObject* self, PyObject *args) {

    PyTensor* t1;
    PyTensor* t2;

    if (!PyArg_ParseTuple(args, "OO", &t1, &t2)) {
        PyErr_SetString(PyExc_TypeError, "Inputs should be Sail Tensors");
        return NULL;
    }

    BINARY_TENSOR_TYPE_CHECK(t1, t2);

    PyTensor* ret_class;
    ret_class = (PyTensor *) PyTensorType.tp_alloc(&PyTensorType, 0);

    ret_class->tensor = ((PyTensor*)t1)->tensor * ((PyTensor*)t2)->tensor;

    ret_class->ndim = ((PyTensor*)t1)->ndim;
    ret_class->dtype = ((PyTensor*)t1)->dtype;

    return (PyObject *) ret_class;
}



RETURN_OBJECT ops_div(PyObject* self, PyObject *args) {

    PyTensor* t1;
    PyTensor* t2;

    if (!PyArg_ParseTuple(args, "OO", &t1, &t2)) {
        PyErr_SetString(PyExc_TypeError, "Inputs should be Sail Tensors");
        return NULL;
    }

    BINARY_TENSOR_TYPE_CHECK(t1, t2);

    PyTensor* ret_class;
    ret_class = (PyTensor *) PyTensorType.tp_alloc(&PyTensorType, 0);

    ret_class->tensor = ((PyTensor*)t1)->tensor / ((PyTensor*)t2)->tensor;

    ret_class->ndim = ((PyTensor*)t1)->ndim;
    ret_class->dtype = ((PyTensor*)t1)->dtype;

    return (PyObject *) ret_class;
}

/** end block **/


