import argparse
from linter import execute
def parse_args():

    parser = argparse.ArgumentParser(description="clang-tidy wrapper")
    
    parser.add_argument(
        "--config-file",
        required=True,
        help="Path to a clang-tidy config file. Defaults to '.clang-tidy'.",
    )
    parser.add_argument(
        "--base-path",
        default="sail/csrc/core",
        help="Base path to search for files to use",
    )
    parser.add_argument(
        "--include",
        help="Single file to use",
    )
    parser.add_argument(
        "--diff-file",
        help="File with list of files changed. Generated by the pre-commit",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    parser.add_argument("-no-clang", "--no-clang", action="store_true", help="Ignore clang-tidy")
    parser.add_argument("-no-custom", "--no-custom", action="store_true", help="Ignore custom linter")
   
    return parser.parse_args()


def run():
    print ("Starting Linter")
    options = parse_args()
    execute(options)
    # if (not options.no_custom):
        # execute_custom(options)

if __name__ == "__main__":
    run()