from sail import Tensor 
from typing import List, Set, Dict, Tuple, Optional, Type


def uniform(min: float, max: float, shape: Tuple) -> Tensor: ...
def normal(mean: float, std: float, shape: Tuple) -> Tensor: ...
def uniform_like(tensor: Tensor, min: float, max: float) -> Tensor: ...
def normal_like(tensor: Tensor, mean: float, std: float) -> Tensor: ...
