# This is a basic workflow to help you get started with Actions

name: CI

on: [pull_request]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Update apt
        run: 'sudo apt-get update'

      - name: Get specific version CMake, v3.14.0
        uses: lukka/get-cmake@v3.14.0   ⟸ THIS IS THE ONE LINER YOU NEED

      - name: Install boost
        uses: MarkusJx/install-boost@v1.0.1
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here: 
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: 1.73.0
          # OPTIONAL: Specify a toolset on windows
          # OPTIONAL: Specify a custon install location
          boost_install_dir: C:\boost

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Build Package
        run: python setup.py install
      
      - name: Test Package
        run: ./test.sh python

