# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
        
      - name: Install gcc-8
        run: sudo apt-get install gcc-8 g++-8
        
      - name: Set gcc option
        run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
      - name: Set gcc default
        run: sudo update-alternatives --set gcc /usr/bin/gcc-8
        
      - name: Set g++ option
        run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
      - name: Set g++ default
        run: sudo update-alternatives --set g++ /usr/bin/g++-8
        
      - name: Install cuda toolkit
        run: sudo apt update && sudo apt install nvidia-cuda-toolkit
#       - name: cuda-toolkit
#         uses: Jimver/cuda-toolkit@v0.2.1
#         with:
#           # Cuda version
#           cuda: 11.2.2

      - name: get-cmake
        uses: lukka/get-cmake@v3.20.1
          
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
          
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build Package
        run: |
          python setup.py install
#       - name: Run Test Suite
#         run: |
#           chmod +x test.sh
#           ./test.sh
