# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: python:3.8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Update apt
        run: 'sudo apt-get update'

      - name: Setup install files
        run: 'chmod +x builder/install_cmake.sh && chmod +x builder/install_gcc.sh'

      - name: Run install files
        run: './builder/install_cmake.sh && ./builder/install_gcc.sh'
