
name: CI

on: 
  pull_request:
      branches: [master]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Update apt
        run: 'sudo apt-get update'

      - name: Setup install files
        run: 'chmod +x .github/workflow_tools/install.sh'

      - name: Run install files
        run: 'sudo ./builder/install.sh'

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build Package
        run: python setup.py install
        
      - name: Deploy 1
        run: |
            cd docs
            make html
            cd _build/html/
            touch .nojekyll
            cd ../../../
      - name: Deploy 2
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs/_build/html'
          destination-github-username: 'sail-ml'
          destination-repository-name: 'sail-ml.github.io'
          user-email: tgsiegel@umd.edu
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
        
