# This is a basic workflow to help you get started with Actions

name: CI

on: [pull_request]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Update apt
        run: 'sudo apt-get update'

      - name: Setup install files
        run: 'chmod +x builder/install.sh'

      - name: Run install files
        run: 'sudo ./builder/install.sh'

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Build Package
        run: python setup.py install
      
      # - name: Test Package
      #   run: ./test.sh python

