
name: CI

on: 
  pull_request:
      branches: [master]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Update apt
        run: 'sudo apt-get update'

      - name: Setup install files
        run: 'chmod +x builder/install.sh'

      - name: Run install files
        run: 'sudo ./builder/install.sh'

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Build Package
        run: python setup.py install
        
      - name: build docs
        run: |
          cd docs
          make html

      - name: Deploy
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'tgs266'
          destination-repository-name: 'sail-documentation'
          user-email: tgsiegel@umd.edu
          target-branch: master

      # - name: Test Package
      #   run: ./test.sh python
